Repository xLucaspx/gcs-t1, pull requests merged in 2024-10, with the labels that each got.

#42 Hotfix: métodos `escolheUsuario` e `deletaItem`
  docs/class-diagram.asta
  src/app/App.java
  src/handler/ItemHandler.java
  src/handler/JogadorHandler.java
  src/model/Item.java
  src/model/Jogador.java
  src/model/StatusProposta.java
Labels: bug, enhancement

#43 Adicionando documentacao no metodo precoTotal da classe ItemHandler
  src/handler/ItemHandler.java
Labels: documentation

#44 Hotfix: Tratamento de exceções
  src/Main.java
  src/app/App.java
Labels: bug

#45 Funcionalidades adicionais: Buscar itens por preço e cancelar propostas realizadas
  docs/class-diagram.asta
  resources/seeder.txt
  src/app/App.java
  src/handler/ItemHandler.java
  src/handler/JogadorHandler.java
  src/handler/PropostaHandler.java
  src/model/Item.java
  src/model/Jogador.java
  src/model/Proposta.java
  src/model/StatusProposta.java
Labels: enhancement

#46 Atualizando documentação e diagrama de classes
  docs/class-diagram.asta
  readme.md
  src/handler/ItemHandler.java
Labels: documentation

#47 Versão 1.1 do sistema
  docs/class-diagram.asta
  readme.md
  resources/seeder.txt
  src/app/App.java
  src/handler/ItemHandler.java
  src/handler/PropostaHandler.java
  src/model/Proposta.java
  src/model/StatusProposta.java
Labels: enhancement
